// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZGEP2YjmHip1a-nTKnRn48j3wWM9HZ2w',
    appId: '1:156416546526:web:572734c66e818e7875944f',
    messagingSenderId: '156416546526',
    projectId: 'donezo-50470',
    authDomain: 'donezo-50470.firebaseapp.com',
    storageBucket: 'donezo-50470.appspot.com',
    measurementId: 'G-1TSPS92N4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhX7RnHDWjR94v0hR1Bl4U-lgS4ADdAVM',
    appId: '1:156416546526:android:3ff652443d10f17c75944f',
    messagingSenderId: '156416546526',
    projectId: 'donezo-50470',
    storageBucket: 'donezo-50470.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgcS9_l4szM0UBFw9E4X6A79bgYnFNza0',
    appId: '1:156416546526:ios:2a348df6a2a60c8475944f',
    messagingSenderId: '156416546526',
    projectId: 'donezo-50470',
    storageBucket: 'donezo-50470.appspot.com',
    iosBundleId: 'com.donezo.donezo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgcS9_l4szM0UBFw9E4X6A79bgYnFNza0',
    appId: '1:156416546526:ios:2a348df6a2a60c8475944f',
    messagingSenderId: '156416546526',
    projectId: 'donezo-50470',
    storageBucket: 'donezo-50470.appspot.com',
    iosBundleId: 'com.donezo.donezo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZGEP2YjmHip1a-nTKnRn48j3wWM9HZ2w',
    appId: '1:156416546526:web:2236bd6bc76c64eb75944f',
    messagingSenderId: '156416546526',
    projectId: 'donezo-50470',
    authDomain: 'donezo-50470.firebaseapp.com',
    storageBucket: 'donezo-50470.appspot.com',
    measurementId: 'G-14J95Q6ZXM',
  );
}
